name: build and publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  rspec_before_build:
    if: github.event.base_ref == 'refs/heads/main'
    uses: ./.github/workflows/_rspec.yml
  release:
    if: github.event.base_ref == 'refs/heads/main'
    needs: rspec_before_build
    runs-on: ubuntu-latest
    steps:
      - name: setup ruby
        uses: ruby/setup-ruby@v1.100.0
        with:
          ruby-version: 3.1.1
      - name: checkout
        uses: actions/checkout@v2
      # - run: bundle install
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          # Be explicit with the gem name
          echo "gem build bundler-fixture.gemspec"
          # Be explicit with the version. Will fail if Bundler::Fixture::VERSION is not the same.
          echo "gem push bundler-fixture-${TAG_NAME##v}.gem"
        env:
          TAG_NAME: "${{github.ref_name}}"
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
