name: build and publish
on:
  push:
    tags:
      - 'v(\d+).(\d+).(\d+)'

jobs:
  rspec:
    if: github.event.push.base_ref == 'refs/heads/main'
    uses: ./.github/workflows/_rspec.yml
  release:
    if: github.event.push.base_ref == 'refs/heads/main'
    needs: rspec
    runs-on: ubuntu-latest
    steps:
      - name: setup ruby
        uses: ruby/setup-ruby@v1.100.0
      - name: checkout
        uses: actions/checkout@v2
      - run: bundle install
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          echo "gem build bundler-fixture.gemspec"
          echo "gem push bundler-fixture-${{github.ref_name#^v}}.gem"
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
