name: rspec
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  test:
    if: github.event.pull_request.action != 'closed' || github.event.pull_request.merged == true
    steps:
      - uses: ./.github/workflows/_rspec
